# Generated by Django 5.2.11 on 2026-02-18 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('current_turn', models.CharField(choices=[('white', 'White'), ('black', 'Black')], default='white', max_length=5)),
                ('status', models.CharField(choices=[('waiting', 'Waiting to start'), ('active', 'Active'), ('check', 'Check'), ('checkmate', 'Checkmate'), ('stalemate', 'Stalemate')], default='waiting', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=5, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChessPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pawn', 'Pawn'), ('rook', 'Rook'), ('knight', 'Knight'), ('bishop', 'Bishop'), ('queen', 'Queen'), ('king', 'King')], max_length=10)),
                ('color', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=5)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('is_captured', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('has_moved', models.BooleanField(default=False)),
                ('en_passant_vulnerable', models.BooleanField(default=False)),
                ('has_castled', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='chess.game')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_x', models.IntegerField()),
                ('from_y', models.IntegerField()),
                ('to_x', models.IntegerField()),
                ('to_y', models.IntegerField()),
                ('move_number', models.IntegerField()),
                ('notation', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_castle', models.BooleanField(default=False)),
                ('is_en_passant', models.BooleanField(default=False)),
                ('is_promotion', models.BooleanField(default=False)),
                ('promotion_piece', models.CharField(blank=True, choices=[('pawn', 'Pawn'), ('rook', 'Rook'), ('knight', 'Knight'), ('bishop', 'Bishop'), ('queen', 'Queen'), ('king', 'King')], max_length=10, null=True)),
                ('captured_piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_by', to='chess.chesspiece')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='chess.game')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='chess.chesspiece')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='black_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_games', to='chess.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='white_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_games', to='chess.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='chess.player'),
        ),
        migrations.CreateModel(
            name='CapturedPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess.chesspiece')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_pieces', to='chess.game')),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='chess.player')),
            ],
        ),
    ]
