# Generated by Django 5.2.11 on 2026-03-03 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting to start'), ('active', 'Active'), ('check', 'Check'), ('checkmate', 'Checkmate'), ('stalemate', 'Stalemate'), ('resigned', 'Resigned')], default='waiting', max_length=10),
        ),
        migrations.CreateModel(
            name='DrawOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_offers', to='chess.game')),
                ('offering_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_draws', to='chess.player')),
            ],
            options={
                'ordering': ['-offered_at'],
            },
        ),
    ]
