# Generated by Django 5.2.11 on 2026-03-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_alter_game_status_drawoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting to start'), ('active', 'Active'), ('check', 'Check'), ('checkmate', 'Checkmate'), ('stalemate', 'Stalemate'), ('resigned', 'Resigned'), ('draw', 'Draw')], default='waiting', max_length=10),
        ),
    ]
